notifications:
  email:
    on_success: always
script: 'bundle exec rake test features'
rvm:
  - 1.9.2
  - 1.9.3
  - 1.8.7
  - ree
  - 2.0.0
branches:
  only:
    - 'master'
    - 'gli-2'
    - 'quick-bugifxes'
