services:
  app:
    image: ${IMAGE}
    build:
      context: "./"
      dockerfile: "Dockerfile.dx"
    platform: ${DOCKER_DEFAULT_PLATFORM}
    pull_policy: "missing"
    init: true
    volumes:
      - type: bind
        source: "./"
        target: "/root/work"
        consistency: "consistent"
    entrypoint: /root/show-help-in-app-container-then-wait.sh
    working_dir: /root/work

